name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Environment
      uses: ./.github/actions/setup

  build_linux:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build Project for Linux
      uses: ./.github/actions/build_linux

  build_windows:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build Project for Windows
      uses: ./.github/actions/build_windows

  build_macos:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build Project for macOS
      uses: ./.github/actions/build_macos
